// GENERATED by rex-codegen — do not edit by hand.
import init, { RexApp } from "rex-runtime/wasm";
import {
  BrowserDriver, Shaper, encodeText, decodeText, encodeAtom, encodeInt, encodeMoney, encodeRel,
  decodeInt, decodeMoney, decodeAtom,
  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,
  type DomDriver, type EventArg, type ShapeNode,
} from "rex-dom";
import { boot, IndexedDbAdapter, MemoryAdapter, profiler, programKey } from "rex-runtime";
import PROGRAM from "./board.rex?raw";

await init();
const store = new URLSearchParams(location.search).has("ephemeral") || import.meta.env.VITE_REX_PERSIST === "0"
  ? new MemoryAdapter()
  : new IndexedDbAdapter(programKey("board", PROGRAM));
const prof = profiler(new URLSearchParams(location.search).has("profile"));
const engine = await boot({ RexApp, program: PROGRAM, adapter: store, profiler: prof });
(window as unknown as { __rexApp: typeof engine }).__rexApp = engine;
const driver = new BrowserDriver();
const container = document.getElementById("app")!;
function dispatch(name: string, args: Record<string, EventArg>): readonly string[] | null {
  let res;
  try {
    res = engine.dispatch(name, args);
  } catch (invalid) {
    console.error(`[rex] dispatch of ${name} failed:`, invalid);
    return null;
  }
  if (res.rejected !== undefined) {
    console.info(`[rex] ${name} rejected: ${res.rejected}`);
    return null;
  }
  if (prof) prof.shaper(() => shaper.applyStep(res.deltas));
  else shaper.applyStep(res.deltas);
  return res.ids;
}

let proto_shape_board_list_card: HTMLElement | undefined;
function build_shape_board_list_card(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("div");
  e0.className = "card";
  const e1 = d.createElement("input");
  e0.appendChild(e1);
  const e2 = d.createElement("button");
  e2.appendChild(document.createTextNode("x"));
  e0.appendChild(e2);
  return e0;
}

const shape_board_list_card: ShapeNode<HTMLElement> = {
  name: "board#list#card",
  membershipView: "board#list#card",
  orderView: "board#list#card#order",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_board_list_card ??= build_shape_board_list_card(d));
    e0.dataset.key = key;
    makeDraggable(e0, key);
    ((e0.childNodes[0] as HTMLElement)).addEventListener("change", (ev) => {
      const p_v = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      { const _r = dispatch("RenameCard", { "card": key, "title": p_v }); if (_r === null) return; _ids.push(..._r); }
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      { const _r = dispatch("DeleteCard", { "card": key }); if (_r === null) return; _ids.push(..._r); }
    });
    return e0;
  },
  attrs: [
    {
      view: "board#list#card#title",
      apply: (_d, el, v) => {
        const _i = ((el.childNodes[0] as HTMLElement)) as HTMLInputElement;
        const _s = String(decodeText(v));
        if (_i.value !== _s) _i.value = _s;
        _i.defaultValue = _s;
      },
    },
  ],
  children: [],
};

let proto_shape_board_list: HTMLElement | undefined;
function build_shape_board_list(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("section");
  e0.className = "list";
  const e1 = d.createElement("header");
  const e2 = d.createElement("span");
  e1.appendChild(e2);
  const e3 = d.createElement("button");
  e3.appendChild(document.createTextNode("+ card"));
  e1.appendChild(e3);
  e0.appendChild(e1);
  return e0;
}

const shape_board_list: ShapeNode<HTMLElement> = {
  name: "board#list",
  membershipView: "board#list",
  orderView: "board#list#order",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_board_list ??= build_shape_board_list(d));
    e0.dataset.key = key;
    makeDropTarget(e0);
    (e0).addEventListener("drop", (ev) => {
      const p_card = dragValue(ev);
      const p_pos = encodeText(dropPos(shaper, "board#list#card", key, (ev as DragEvent).clientY, p_card));
      const _ids: string[] = [];
      { const _r = dispatch("MoveCard", { "card": p_card, "list": key, "pos": p_pos }); if (_r === null) return; _ids.push(..._r); }
      maybeRebalance(engine, shaper, "board#list#card", key, "pos", encodeText);
    });
    (((e0.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).addEventListener("click", (ev) => {
      const p_pos = encodeText(endOf(shaper, "board#list#card", key));
      const _ids: string[] = [];
      { const _r = dispatch("AddCard", { "list": key, "pos": p_pos }); if (_r === null) return; _ids.push(..._r); }
      for (const _id of _ids) { const _el = shaper.el("board#list#card", _id); if (_el) { (_el.querySelector("input, textarea") as HTMLElement | null)?.focus(); break; } }
      maybeRebalance(engine, shaper, "board#list#card", key, "pos", encodeText);
    });
    return e0;
  },
  attrs: [
    {
      view: "board#list#title",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
  ],
  children: [shape_board_list_card],
};

const shaper = new Shaper<HTMLElement>(driver, container, [shape_board_list]);
shaper.applyStep(engine.snapshot());
