// GENERATED by rex-codegen — do not edit by hand.
import init, { RexApp } from "./pkg/rex_wasm.js";
import {
  BrowserDriver, Shaper, parseStepJson, encodeText, decodeText, encodeAtom,
  decodeInt, decodeMoney, decodeAtom,
  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,
  type ShapeNode,
} from "rex-dom";
import PROGRAM from "./board.rex?raw";

await init();
const app = new RexApp(PROGRAM);
const driver = new BrowserDriver();
const container = document.getElementById("app")!;
const apply = (json: string) => shaper.applyStep(parseStepJson(json));
function dispatch(name: string, args: Record<string, string>): string[] {
  const res = JSON.parse(app.dispatch(name, JSON.stringify(args)));
  shaper.applyStep(res.deltas.views);
  return res.ids as string[];
}

const shape_board_list_card: ShapeNode<HTMLElement> = {
  name: "board#list#card",
  membershipView: "board#list#card",
  orderView: "board#list#card#order",
  template: (d, key) => {
    const e0 = d.createElement("div");
    e0.className = "card";
    makeDraggable(e0, key);
    const e1 = d.createElement("input");
    e0.appendChild(e1);
    const e2 = d.createElement("button");
    e2.appendChild(document.createTextNode("x"));
    e0.appendChild(e2);
    e0.dataset.key = key;
    ((e0.childNodes[0] as HTMLElement)).addEventListener("change", (ev) => {
      const v = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids = dispatch("board#list#card@change3", { "c": key, "v": v });
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids = dispatch("board#list#card@click4", { "c": key });
    });
    return e0;
  },
  attrs: [
    {
      view: "board#list#card#title",
      apply: (_d, el, v) => {
        const _i = ((el.childNodes[0] as HTMLElement)) as HTMLInputElement;
        const _s = String(decodeText(v));
        if (_i.value !== _s) _i.value = _s;
      },
    },
  ],
  children: [],
};

const shape_board_list: ShapeNode<HTMLElement> = {
  name: "board#list",
  membershipView: "board#list",
  orderView: "board#list#order",
  template: (d, key) => {
    const e0 = d.createElement("section");
    e0.className = "list";
    makeDropTarget(e0);
    const e1 = d.createElement("header");
    const e2 = d.createElement("span");
    e1.appendChild(e2);
    const e3 = d.createElement("button");
    e3.appendChild(document.createTextNode("+ card"));
    e1.appendChild(e3);
    e0.appendChild(e1);
    e0.dataset.key = key;
    (e0).addEventListener("drop", (ev) => {
      const card = dragValue(ev);
      const pos = encodeText(dropPos(shaper, "board#list#card", key, (ev as DragEvent).clientY, card));
      const _ids = dispatch("board#list@drop1", { "l": key, "card": card, "pos": pos });
      maybeRebalance(app, apply, shaper, "board#list#card", key, "pos", encodeText);
    });
    (((e0.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).addEventListener("click", (ev) => {
      const pos = encodeText(endOf(shaper, "board#list#card", key));
      const _ids = dispatch("board#list@click2", { "l": key, "pos": pos });
      shaper.el("board#list#card", _ids[0])?.querySelector("input, textarea")?.focus();
      maybeRebalance(app, apply, shaper, "board#list#card", key, "pos", encodeText);
    });
    return e0;
  },
  attrs: [
    {
      view: "board#list#title",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
  ],
  children: [shape_board_list_card],
};

const shaper = new Shaper<HTMLElement>(driver, container, [shape_board_list]);
shaper.applyStep(parseStepJson(app.snapshot()));
