//! The Rex UI compiler: a `.rex` program with `view`s becomes a self-contained
//! TypeScript module that drives the DOM through `rex-dom`'s `Shaper` and the
//! wasm `RexApp` (§M5).
//!
//! The compiler is a dumb emitter over the [`ShapeProgram`] the checker
//! produces — no naming logic, no re-derivation. The emitted module embeds the
//! program source (single artifact), builds one `ShapeNode` per level, wires
//! event listeners to `app.dispatch`, and mounts.

use rex::ast::Extractor;
use rex::diagnostic::{Diagnostic, Severity};
use rex::types::shape_ir::*;

fn has_error(ds: &[Diagnostic]) -> bool {
    ds.iter().any(|d| d.severity == Severity::Error)
}

/// Compile a `.rex` source into a TS module string. `program_import` is the
/// import specifier for the raw program source (e.g. `"./board.rex?raw"`).
/// Returns the module text, or the checker's diagnostics on failure.
pub fn generate(source: &str, program_import: &str) -> Result<String, Vec<Diagnostic>> {
    generate_with(source, program_import, false)
}

/// Like [`generate`], but `debug` emits `console.debug` tracing at the engine
/// boundary (every dispatch: handler name, args, minted ids, delta view names)
/// so a running app can be traced back to the `.rex` handler that fired.
pub fn generate_with(
    source: &str,
    program_import: &str,
    debug: bool,
) -> Result<String, Vec<Diagnostic>> {
    let parsed = rex::parse(source);
    if has_error(&parsed.diagnostics) {
        return Err(parsed.diagnostics);
    }
    let checked = rex::check(&parsed.program);
    if checked.elaborated.is_none() {
        return Err(checked.diagnostics);
    }
    Ok(emit(&checked.shapes, program_import, debug))
}

fn emit(shapes: &ShapeProgram, program_import: &str, debug: bool) -> String {
    let mut e = Emit {
        out: String::new(),
        shapes,
        debug,
    };
    e.preamble(program_import);
    // Emit levels post-order so a child const precedes its parent.
    let mut roots = Vec::new();
    for view in &shapes.views {
        e.level(view);
        roots.push(var_name(&view.name));
    }
    e.mount(&roots);
    e.out
}

struct Emit<'a> {
    out: String,
    shapes: &'a ShapeProgram,
    debug: bool,
}

impl Emit<'_> {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn preamble(&mut self, program_import: &str) {
        self.line("// GENERATED by rex-codegen — do not edit by hand.");
        self.line("import init, { RexApp } from \"./pkg/rex_wasm.js\";");
        self.line("import {");
        self.line("  BrowserDriver, Shaper, parseStepJson, encodeText, decodeText, encodeAtom,");
        self.line("  decodeInt, decodeMoney, decodeAtom,");
        self.line("  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,");
        self.line("  type ShapeNode,");
        self.line("} from \"rex-dom\";");
        self.line(&format!("import PROGRAM from \"{program_import}\";"));
        self.line("");
        self.line("await init();");
        self.line("const app = new RexApp(PROGRAM);");
        self.line("const driver = new BrowserDriver();");
        self.line("const container = document.getElementById(\"app\")!;");
        self.line("const apply = (json: string) => shaper.applyStep(parseStepJson(json));");
        self.line("function dispatch(name: string, args: Record<string, string>): string[] {");
        if self.debug {
            self.line("  console.debug(\"[rex] dispatch\", name, args);");
        }
        self.line("  const res = JSON.parse(app.dispatch(name, JSON.stringify(args)));");
        if self.debug {
            self.line("  console.debug(\"[rex]  ->\", name, \"ids:\", res.ids, \"views:\", Object.keys(res.deltas.views));");
        }
        self.line("  shaper.applyStep(res.deltas.views);");
        self.line("  return res.ids as string[];");
        self.line("}");
        self.line("");
    }

    /// Emit one level's `ShapeNode` const (children first).
    fn level(&mut self, level: &ShapeLevel) {
        for child in &level.children {
            self.level(child);
        }
        let var = var_name(&level.name);
        self.line(&format!(
            "const {var}: ShapeNode<HTMLElement> = {{"
        ));
        self.line(&format!("  name: {},", js_str(&level.name)));
        self.line(&format!("  membershipView: {},", js_str(&level.membership_view)));
        if let Some(o) = &level.order_view {
            self.line(&format!("  orderView: {},", js_str(o)));
        }
        self.template(level);
        self.attrs(level);
        let kids: Vec<String> = level.children.iter().map(|c| var_name(&c.name)).collect();
        self.line(&format!("  children: [{}],", kids.join(", ")));
        self.line("};");
        self.line("");
    }

    fn template(&mut self, level: &ShapeLevel) {
        self.line("  template: (d, key) => {");
        // Build the DOM skeleton; e0 is the root.
        let mut b = TemplateBuilder { emit_lines: Vec::new(), counter: 0 };
        b.build(&level.template, None);
        for l in &b.emit_lines {
            self.line(&format!("    {l}"));
        }
        self.line("    e0.dataset.key = key;");
        // Event listeners, navigated from e0 by child-index path.
        for ev in &level.events {
            self.event(level, ev);
        }
        self.line("    return e0;");
        self.line("  },");
    }

    fn event(&mut self, level: &ShapeLevel, ev: &EventBinding) {
        let target = nav_expr("e0", &ev.path);
        let handler = self
            .shapes
            .handlers
            .iter()
            .find(|h| h.name == ev.handler)
            .expect("handler exists");
        self.line(&format!(
            "    ({target}).addEventListener({}, (ev) => {{",
            js_str(&dom_event(ev))
        ));
        // Materialize each arg into a local (order preserved for dependencies).
        for a in &ev.args {
            let expr = self.arg_expr(level, a);
            self.out
                .push_str(&format!("      const {} = {expr};\n", a.name));
        }
        // Build the dispatch args object: self binder key + params.
        let mut fields = Vec::new();
        for (binder, _) in &handler.binders {
            fields.push(format!("{}: key", js_str(binder)));
        }
        for a in &ev.args {
            fields.push(format!("{}: {}", js_str(&a.name), a.name));
        }
        self.line(&format!(
            "      const _ids = dispatch({}, {{ {} }});",
            js_str(&ev.handler),
            fields.join(", ")
        ));
        // Auto-focus a freshly inserted, editable row (the "+ card" idiom).
        self.focus_inserts(handler);
        // Amortized rebalance of any ordered child levels under this row.
        for child in &level.children {
            if let (Some(_), Some(field)) = (&child.order_view, &child.order_field) {
                self.line(&format!(
                    "      maybeRebalance(app, apply, shaper, {}, key, {}, encodeText);",
                    js_str(&child.name),
                    js_str(field)
                ));
            }
        }
        self.line("    });");
    }

    /// After a handler that creates entities, focus the first input of each
    /// newly mounted row that some level renders — the natural "new item is
    /// ready to edit" behavior.
    fn focus_inserts(&mut self, handler: &HandlerDef) {
        let mut insert_idx = 0;
        for m in &handler.body {
            if let MutationIR::Insert { entity, .. } = m {
                if let Some(level_name) = self.level_for_entity(entity) {
                    self.line(&format!(
                        "      shaper.el({}, _ids[{insert_idx}])?.querySelector(\"input, textarea\")?.focus();",
                        js_str(&level_name)
                    ));
                }
                insert_idx += 1;
            }
        }
    }

    fn level_for_entity(&self, entity: &str) -> Option<String> {
        fn search(level: &ShapeLevel, entity: &str) -> Option<String> {
            if level.entity == entity {
                return Some(level.name.clone());
            }
            level.children.iter().find_map(|c| search(c, entity))
        }
        self.shapes.views.iter().find_map(|v| search(v, entity))
    }

    fn arg_expr(&self, _level: &ShapeLevel, a: &ArgSpec) -> String {
        // `endOf`/`dropPos` name the child level they range over; the
        // desugarer has already resolved the surface binder to a level name.
        let raw = match &a.extractor {
            Extractor::Value => "(ev.currentTarget as HTMLInputElement).value".to_string(),
            Extractor::Checked => {
                return "((ev.currentTarget as HTMLInputElement).checked ? encodeAtom(\"true\") : encodeAtom(\"false\"))".to_string()
            }
            Extractor::Drag(_) => return "dragValue(ev)".to_string(),
            Extractor::DropPos { level, exclude } => format!(
                "dropPos(shaper, {}, key, (ev as DragEvent).clientY, {})",
                js_str(level),
                exclude
            ),
            Extractor::EndOf(level) => format!("endOf(shaper, {}, key)", js_str(level)),
            // Rejected by the desugarer until S-42 wires `import js` through.
            Extractor::Js { module, func, .. } => format!("{module}.{func}()"),
        };
        // Encode per the arg's declared encoding.
        match a.encoding {
            Encoding::Text => format!("encodeText({raw})"),
            Encoding::Atom => format!("encodeAtom({raw})"),
            Encoding::Id => raw,
            Encoding::Int | Encoding::Money => raw,
        }
    }

    fn attrs(&mut self, level: &ShapeLevel) {
        self.line("  attrs: [");
        for a in &level.attrs {
            let t = nav_expr("el", &a.path);
            self.line("    {");
            self.line(&format!("      view: {},", js_str(&a.view)));
            self.line("      apply: (_d, el, v) => {");
            let decode = decode_fn(a.encoding);
            match &a.kind {
                BindKind::Text => {
                    self.line(&format!("        ({t}).textContent = String({decode}(v));"));
                }
                BindKind::Prop(prop) if prop == "value" => {
                    self.line(&format!("        const _i = ({t}) as HTMLInputElement;"));
                    self.line(&format!("        const _s = String({decode}(v));"));
                    self.line("        if (_i.value !== _s) _i.value = _s;");
                }
                BindKind::Prop(prop) if prop == "checked" => {
                    self.line(&format!("        ({t} as HTMLInputElement).checked = (v === encodeAtom(\"true\"));"));
                }
                BindKind::Prop(prop) => {
                    self.line(&format!("        ({t} as any).{prop} = {decode}(v);"));
                }
                BindKind::Class(cls) => {
                    self.line(&format!(
                        "        ({t}).classList.toggle({}, v === encodeAtom(\"true\"));",
                        js_str(cls)
                    ));
                }
            }
            self.line("      },");
            self.line("    },");
        }
        self.line("  ],");
    }

    fn mount(&mut self, roots: &[String]) {
        self.line(&format!(
            "const shaper = new Shaper<HTMLElement>(driver, container, [{}]);",
            roots.join(", ")
        ));
        self.line("shaper.applyStep(parseStepJson(app.snapshot()));");
    }
}

/// Builds a level's DOM skeleton into JS statement lines. `e0` is the root.
struct TemplateBuilder {
    emit_lines: Vec<String>,
    counter: usize,
}

impl TemplateBuilder {
    /// Emit statements creating `tpl` as element `e{n}`; if `parent` is set,
    /// append to it. Returns the var index used.
    fn build(&mut self, tpl: &Tpl, parent: Option<usize>) -> usize {
        match tpl {
            Tpl::Elem { tag, classes, modifiers, attrs, children } => {
                let n = self.counter;
                self.counter += 1;
                // Every element goes through the driver (`d`) so a template is
                // driver-agnostic; only text nodes use the DOM directly (the
                // driver models elements, not text nodes).
                self.emit_lines
                    .push(format!("const e{n} = d.createElement({});", js_str(tag)));
                if !classes.is_empty() {
                    self.emit_lines
                        .push(format!("e{n}.className = {};", js_str(&classes.join(" "))));
                }
                for (k, val) in attrs {
                    self.emit_lines
                        .push(format!("e{n}.setAttribute({}, {});", js_str(k), js_str(val)));
                }
                for m in modifiers {
                    match m.as_str() {
                        "draggable" => self.emit_lines.push(format!("makeDraggable(e{n}, key);")),
                        "dropTarget" => self.emit_lines.push(format!("makeDropTarget(e{n});")),
                        other => self
                            .emit_lines
                            .push(format!("e{n}.classList.add({});", js_str(other))),
                    }
                }
                for child in children {
                    self.build(child, Some(n));
                }
                if let Some(p) = parent {
                    self.emit_lines.push(format!("e{p}.appendChild(e{n});"));
                }
                n
            }
            Tpl::Static(s) => {
                let p = parent.expect("static text needs a parent element");
                self.emit_lines
                    .push(format!("e{p}.appendChild(document.createTextNode({}));", js_str(s)));
                usize::MAX
            }
        }
    }
}

/// `on keydown.enter` -> `"keydown"` (event modifiers are handled in the
/// listener body, not the event name).
fn dom_event(ev: &EventBinding) -> String {
    ev.dom_event.clone()
}

/// The `rex-dom` decode function for a bind's wire encoding (an `Id` passes
/// through already-encoded, so it shares `decodeText`'s no-op-on-non-`t:`
/// behavior rather than needing its own decoder).
fn decode_fn(encoding: Encoding) -> &'static str {
    match encoding {
        Encoding::Text | Encoding::Id => "decodeText",
        Encoding::Int => "decodeInt",
        Encoding::Money => "decodeMoney",
        Encoding::Atom => "decodeAtom",
    }
}

/// A child-index navigation expression from `root` down a path.
fn nav_expr(root: &str, path: &[usize]) -> String {
    if path.is_empty() {
        return root.to_string();
    }
    let mut expr = root.to_string();
    for &i in path {
        expr = format!("({expr}.childNodes[{i}] as HTMLElement)");
    }
    expr
}

/// A JS/TS-safe variable name for a `#`/`@`-separated level name.
fn var_name(name: &str) -> String {
    let mut s = String::from("shape_");
    for ch in name.chars() {
        s.push(if ch.is_ascii_alphanumeric() { ch } else { '_' });
    }
    s
}

/// A JSON/JS string literal.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}
