//! The Rex UI compiler: a `.rex` program with `view`s becomes a self-contained
//! TypeScript module that drives the DOM through `rex-dom`'s `Shaper` and the
//! wasm `RexApp` (§M5).
//!
//! The compiler is a dumb emitter over the [`ShapeProgram`] the checker
//! produces — no naming logic, no re-derivation. The emitted module embeds the
//! program source (single artifact), builds one `ShapeNode` per level, wires
//! event listeners to `app.dispatch`, and mounts.

use rex::ast::Extractor;
use rex::diagnostic::{Diagnostic, Severity};
use rex::types::shape_ir::*;

fn has_error(ds: &[Diagnostic]) -> bool {
    ds.iter().any(|d| d.severity == Severity::Error)
}

/// Compile a `.rex` source into a TS module string. `program_import` is the
/// import specifier for the raw program source (e.g. `"./board.rex?raw"`).
/// Returns the module text, or the checker's diagnostics on failure.
pub fn generate(source: &str, program_import: &str) -> Result<String, Vec<Diagnostic>> {
    generate_with(source, program_import, false)
}

/// Like [`generate`], but `debug` emits `console.debug` tracing at the engine
/// boundary (every dispatch: event name, args, minted ids, delta view names)
/// so a running app can be traced back to the `.rex` event that fired.
pub fn generate_with(
    source: &str,
    program_import: &str,
    debug: bool,
) -> Result<String, Vec<Diagnostic>> {
    let parsed = rex::parse(source);
    if has_error(&parsed.diagnostics) {
        return Err(parsed.diagnostics);
    }
    let checked = rex::check(&parsed.program);
    if checked.elaborated.is_none() {
        return Err(checked.diagnostics);
    }
    Ok(emit(&checked.shapes, program_import, debug))
}

fn emit(shapes: &ShapeProgram, program_import: &str, debug: bool) -> String {
    let mut e = Emit {
        out: String::new(),
        debug,
    };
    e.preamble(program_import, &shapes.imports);
    // Emit levels post-order so a child const precedes its parent.
    let mut roots = Vec::new();
    for view in &shapes.views {
        e.level(view);
        roots.push(var_name(&view.name));
    }
    e.mount(&roots);
    e.out
}

struct Emit {
    out: String,
    debug: bool,
}

impl Emit {
    fn line(&mut self, s: &str) {
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn preamble(&mut self, program_import: &str, imports: &[rex::types::shape_ir::JsImport]) {
        self.line("// GENERATED by rex-codegen — do not edit by hand.");
        self.line("import init, { RexApp } from \"./pkg/rex_wasm.js\";");
        self.line("import {");
        self.line("  BrowserDriver, Shaper, parseStepJson, encodeText, decodeText, encodeAtom, encodeInt, encodeMoney, encodeRel,");
        self.line("  decodeInt, decodeMoney, decodeAtom,");
        self.line("  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,");
        self.line("  type DomDriver, type ShapeNode,");
        self.line("} from \"rex-dom\";");
        self.line("import { boot, IndexedDbAdapter, MemoryAdapter, profiler, programKey } from \"rex-runtime\";");
        self.line(&format!("import PROGRAM from \"{program_import}\";"));
        for i in imports {
            self.line(&format!("import * as {} from {};", i.alias, js_str(&i.path)));
        }
        self.line("");
        self.line("await init();");
        // State survives a reload (S-80): boot restores from IndexedDB, keyed
        // by the program's source so an edited program starts clean rather
        // than replaying another version's log. `?ephemeral` opts out.
        self.line(&format!(
            "const store = new URLSearchParams(location.search).has(\"ephemeral\") || import.meta.env.VITE_REX_PERSIST === \"0\"\n  ? new MemoryAdapter()\n  : new IndexedDbAdapter(programKey({}, PROGRAM));",
            js_str(&program_name(program_import))
        ));
        self.line("const app = await boot({ RexApp, program: PROGRAM, adapter: store });");
        // `?profile` logs each dispatch's engine / parse / shaper split and
        // exposes them as `window.__rexProfile.timings` (P-0).
        self.line("const prof = profiler(new URLSearchParams(location.search).has(\"profile\"));");
        // A test hook, not a runtime dependency: Playwright inspects the log
        // through this (e.g. asserting a rebalance sweep landed there,
        // S-22) rather than poking at wasm internals.
        self.line("(window as unknown as { __rexApp: RexApp }).__rexApp = app;");
        self.line("const driver = new BrowserDriver();");
        self.line("const container = document.getElementById(\"app\")!;");
        self.line("const apply = (json: string) => shaper.applyStep(parseStepJson(json));");
        self.line("function dispatch(name: string, args: Record<string, unknown>): string[] {");
        if self.debug {
            self.line("  console.debug(\"[rex] dispatch\", name, args);");
        }
        self.line("  const res = prof");
        self.line("    ? prof.dispatch(name, () => app.dispatch(name, JSON.stringify(args)), (r: any) => shaper.applyStep(r.deltas.views))");
        self.line("    : JSON.parse(app.dispatch(name, JSON.stringify(args)));");
        if self.debug {
            self.line("  console.debug(\"[rex]  ->\", name, \"ids:\", res.ids, \"views:\", Object.keys(res.deltas.views));");
        }
        self.line("  if (!prof) shaper.applyStep(res.deltas.views);");
        self.line("  return res.ids as string[];");
        self.line("}");
        self.line("");
    }

    /// Emit one level's `ShapeNode` const (children first).
    fn level(&mut self, level: &ShapeLevel) {
        for child in &level.children {
            self.level(child);
        }
        let var = var_name(&level.name);
        // The level's prototype skeleton, built on first mount.
        let b = TemplateBuilder::skeleton(&level.template);
        self.line(&format!("let proto_{var}: HTMLElement | undefined;"));
        self.line(&format!("function build_{var}(d: DomDriver<HTMLElement>): HTMLElement {{"));
        for l in &b.emit_lines {
            self.line(&format!("  {l}"));
        }
        self.line("  return e0;");
        self.line("}");
        self.line("");
        self.line(&format!(
            "const {var}: ShapeNode<HTMLElement> = {{"
        ));
        self.line(&format!("  name: {},", js_str(&level.name)));
        self.line(&format!("  membershipView: {},", js_str(&level.membership_view)));
        if let Some(o) = &level.order_view {
            self.line(&format!("  orderView: {},", js_str(o)));
            if level.order_desc {
                self.line("  orderDesc: true,");
            }
        }
        if !level.slot.is_empty() {
            self.line(&format!("  slot: (root) => {},", nav_expr("root", &level.slot)));
        }
        self.template(level);
        self.attrs(level);
        let kids: Vec<String> = level.children.iter().map(|c| var_name(&c.name)).collect();
        self.line(&format!("  children: [{}],", kids.join(", ")));
        self.line("};");
        self.line("");
    }

    fn template(&mut self, level: &ShapeLevel) {
        let uses_ancestors = level.events.iter().any(|ev| {
            ev.dispatches
                .iter()
                .any(|d| d.args.iter().any(|(_, a)| matches!(a, ArgRef::Ancestor(_))))
        });
        self.line(&format!(
            "  template: (d, key{}) => {{",
            if uses_ancestors { ", ancestors" } else { "" }
        ));
        // Each row clones a prototype skeleton built once (P-6): one
        // `cloneNode` instead of a `createElement` per element. What a clone
        // cannot carry — listeners, key-specific setup — is applied per row.
        let var = var_name(&level.name);
        let b = TemplateBuilder::skeleton(&level.template);
        self.line(&format!("    const e0 = d.clone(proto_{var} ??= build_{var}(d));"));
        self.line("    e0.dataset.key = key;");
        for l in &b.instance_lines {
            self.line(&format!("    {l}"));
        }
        // Event listeners, navigated from e0 by child-index path.
        for ev in &level.events {
            self.event(level, ev);
        }
        self.line("    return e0;");
        self.line("  },");
    }

    fn event(&mut self, level: &ShapeLevel, ev: &EventBinding) {
        let target = nav_expr("e0", &ev.path);
        self.line(&format!(
            "    ({target}).addEventListener({}, (ev) => {{",
            js_str(&dom_event(ev))
        ));
        // `keydown.enter`: only the named key runs the handler.
        if matches!(ev.dom_event.as_str(), "keydown" | "keyup" | "keypress") && !ev.modifiers.is_empty() {
            let keys: Vec<String> = ev.modifiers.iter().map(|m| js_str(&key_name(m))).collect();
            self.line(&format!(
                "      if (![{}].includes((ev as KeyboardEvent).key)) return;",
                keys.join(", ")
            ));
        }
        // Materialize each param into a local (order preserved for dependencies).
        for a in &ev.params {
            let expr = self.arg_expr(level, a);
            self.out
                .push_str(&format!("      const {} = {expr};\n", a.name));
        }
        // One dispatch per `do`, each its own transaction; ids minted by any
        // of them feed the `focus(c)` action.
        self.line("      const _ids: string[] = [];");
        for d in &ev.dispatches {
            let fields: Vec<String> = d
                .args
                .iter()
                .map(|(name, a)| format!("{}: {}", js_str(name), arg_ref(a)))
                .collect();
            self.line(&format!(
                "      _ids.push(...dispatch({}, {{ {} }}));",
                js_str(&d.event),
                fields.join(", ")
            ));
        }
        for a in &ev.actions {
            match a {
                UiAction::FocusNew { level } => {
                    self.line(&format!(
                        "      for (const _id of _ids) {{ const _el = shaper.el({}, _id); if (_el) {{ (_el.querySelector(\"input, textarea\") as HTMLElement | null)?.focus(); break; }} }}",
                        js_str(level)
                    ));
                }
                UiAction::FocusClass(cls) => {
                    self.line(&format!(
                        "      (e0.querySelector({}) as HTMLElement | null)?.focus();",
                        js_str(&format!(".{cls}"))
                    ));
                }
                UiAction::Revert => {
                    self.line("      { const _i = ev.currentTarget as HTMLInputElement; _i.value = _i.defaultValue; }");
                }
                UiAction::Clear => {
                    self.line("      (ev.currentTarget as HTMLInputElement).value = \"\";");
                }
            }
        }
        // Amortized rebalance of any ordered child levels under this row.
        for child in &level.children {
            if let (Some(_), Some(field)) = (&child.order_view, &child.order_field) {
                self.line(&format!(
                    "      maybeRebalance(app, apply, shaper, {}, key, {}, encodeText);",
                    js_str(&child.name),
                    js_str(field)
                ));
            }
        }
        self.line("    });");
    }

    fn arg_expr(&self, _level: &ShapeLevel, a: &ArgSpec) -> String {
        // `endOf`/`dropPos` name the child level they range over; the
        // desugarer has already resolved the surface binder to a level name.
        let raw = match &a.extractor {
            Extractor::Value => "(ev.currentTarget as HTMLInputElement).value".to_string(),
            // Must spell the same atoms the `checked` bind reads back
            // (`True`/`False`), or the round trip silently un-toggles.
            Extractor::Checked => {
                return format!(
                    "((ev.currentTarget as HTMLInputElement).checked ? encodeAtom({}) : encodeAtom({}))",
                    js_str(rex::types::typed::TRUE),
                    js_str(rex::types::typed::FALSE)
                )
            }
            Extractor::Drag(_) => return "dragValue(ev)".to_string(),
            Extractor::DropPos { level, exclude } => format!(
                "dropPos(shaper, {}, key, (ev as DragEvent).clientY, {})",
                js_str(level),
                exclude
            ),
            Extractor::EndOf(level) => format!("endOf(shaper, {}, key)", js_str(level)),
            // The call is DOM-layer JS; its result is encoded to the wire
            // here, so a logged event carries plain canonical values. A
            // relation-typed param takes an array, keyed by index (S-91).
            Extractor::Js { module, func, args } => {
                let call = format!(
                    "{module}.{func}({})",
                    args.iter().map(js_expr_lit).collect::<Vec<_>>().join(", ")
                );
                return match a.rel_value {
                    Some(v) => format!("encodeRel({call}, {})", encoder(v)),
                    None => format!("{}({call})", encoder(a.encoding)),
                };
            }
        };
        // Encode per the arg's declared encoding.
        match a.encoding {
            Encoding::Text => format!("encodeText({raw})"),
            Encoding::Atom => format!("encodeAtom({raw})"),
            Encoding::Id => raw,
            Encoding::Int | Encoding::Money => raw,
        }
    }

    fn attrs(&mut self, level: &ShapeLevel) {
        self.line("  attrs: [");
        for a in &level.attrs {
            let t = nav_expr("el", &a.path);
            self.line("    {");
            self.line(&format!("      view: {},", js_str(&a.view)));
            // A class gate is applied on absence too, so the shaper must not
            // skip it when the view has no row for this key (S-52).
            if matches!(a.kind, BindKind::Class(_) | BindKind::Flag(_)) {
                self.line("      presence: true,");
            }
            self.line("      apply: (_d, el, v) => {");
            let decode = decode_fn(a.encoding);
            match &a.kind {
                BindKind::Text => {
                    self.line(&format!("        ({t}).textContent = String({decode}(v));"));
                }
                BindKind::Prop(prop) if prop == "value" => {
                    self.line(&format!("        const _i = ({t}) as HTMLInputElement;"));
                    self.line(&format!("        const _s = String({decode}(v));"));
                    self.line("        if (_i.value !== _s) _i.value = _s;");
                    // `revert` restores from the attribute.
                    self.line("        _i.defaultValue = _s;");
                }
                BindKind::Prop(prop) if prop == "checked" => {
                    self.line(&format!(
                        "        ({t} as HTMLInputElement).checked = (v === encodeAtom({}));",
                        js_str(rex::types::typed::TRUE)
                    ));
                }
                BindKind::Prop(prop) => {
                    self.line(&format!("        ({t} as any).{prop} = {decode}(v);"));
                }
                // Presence, not value: the gate view holds the key exactly
                // when the class is on, so `undefined` means off (S-52).
                BindKind::Flag(prop) => {
                    self.line(&format!("        ({t} as any).{prop} = v !== undefined;"));
                }
                BindKind::Class(cls) => {
                    self.line(&format!(
                        "        ({t}).classList.toggle({}, v !== undefined);",
                        js_str(cls)
                    ));
                }
            }
            self.line("      },");
            self.line("    },");
        }
        self.line("  ],");
    }

    fn mount(&mut self, roots: &[String]) {
        self.line(&format!(
            "const shaper = new Shaper<HTMLElement>(driver, container, [{}]);",
            roots.join(", ")
        ));
        self.line("shaper.applyStep(parseStepJson(app.snapshot()));");
    }
}

/// Builds a level's DOM skeleton into JS statement lines. `e0` is the root.
/// `emit_lines` build the shared prototype; `instance_lines` run on each
/// clone of it, against elements navigated from `e0` by child-index path.
struct TemplateBuilder {
    emit_lines: Vec<String>,
    instance_lines: Vec<String>,
    counter: usize,
}

impl TemplateBuilder {
    fn skeleton(tpl: &Tpl) -> TemplateBuilder {
        let mut b = TemplateBuilder { emit_lines: Vec::new(), instance_lines: Vec::new(), counter: 0 };
        b.build(tpl, None, &[]);
        b
    }

    /// Emit statements creating `tpl` as element `e{n}` at child-index
    /// `path` from the root; if `parent` is set, append to it. Returns the
    /// var index used.
    fn build(&mut self, tpl: &Tpl, parent: Option<usize>, path: &[usize]) -> usize {
        match tpl {
            Tpl::Elem { tag, classes, modifiers, attrs, children } => {
                let n = self.counter;
                self.counter += 1;
                let at = nav_expr("e0", path);
                // Every element goes through the driver (`d`) so a template is
                // driver-agnostic; only text nodes use the DOM directly (the
                // driver models elements, not text nodes).
                self.emit_lines
                    .push(format!("const e{n} = d.createElement({});", js_str(tag)));
                if !classes.is_empty() {
                    self.emit_lines
                        .push(format!("e{n}.className = {};", js_str(&classes.join(" "))));
                }
                for (k, val) in attrs {
                    self.emit_lines
                        .push(format!("e{n}.setAttribute({}, {});", js_str(k), js_str(val)));
                }
                for m in modifiers {
                    match m.as_str() {
                        // Listeners and the row key: per clone.
                        "draggable" => self.instance_lines.push(format!("makeDraggable({at}, key);")),
                        "dropTarget" => self.instance_lines.push(format!("makeDropTarget({at});")),
                        // A boolean attribute; a node inserted after load is
                        // not autofocused by the browser, so focus it too.
                        "autofocus" => {
                            self.emit_lines.push(format!("e{n}.setAttribute(\"autofocus\", \"\");"));
                            self.instance_lines.push(format!("{{ const el = {at}; setTimeout(() => el.focus(), 0); }}"));
                        }
                        other => self
                            .emit_lines
                            .push(format!("e{n}.classList.add({});", js_str(other))),
                    }
                }
                for (i, child) in children.iter().enumerate() {
                    let mut child_path = path.to_vec();
                    child_path.push(i);
                    self.build(child, Some(n), &child_path);
                }
                if let Some(p) = parent {
                    self.emit_lines.push(format!("e{p}.appendChild(e{n});"));
                }
                n
            }
            Tpl::Static(s) => {
                let p = parent.expect("static text needs a parent element");
                self.emit_lines
                    .push(format!("e{p}.appendChild(document.createTextNode({}));", js_str(s)));
                usize::MAX
            }
        }
    }
}

/// The `rex-dom` function encoding a JS value of `enc` to the wire.
fn encoder(enc: Encoding) -> &'static str {
    match enc {
        Encoding::Text => "encodeText",
        Encoding::Int => "encodeInt",
        Encoding::Money => "encodeMoney",
        Encoding::Atom => "encodeAtom",
        Encoding::Id => "String",
    }
}

/// A literal extractor argument as JS.
fn js_expr_lit(e: &rex::ast::Expr) -> String {
    match &e.kind {
        rex::ast::ExprKind::Int(n) => n.to_string(),
        rex::ast::ExprKind::Str(s) => js_str(s),
        _ => "undefined".to_string(),
    }
}

/// The listener-local expression for a dispatch argument.
fn arg_ref(a: &ArgRef) -> String {
    match a {
        ArgRef::SelfKey => "key".to_string(),
        // `ancestors[0]` is the parent row's key, `[1]` its parent's, …
        ArgRef::Ancestor(n) => format!("ancestors[{}]", n - 1),
        ArgRef::Param(p) => p.clone(),
        ArgRef::Lit(l) => js_lit(l),
    }
}

/// A literal dispatch argument in canonical wire encoding.
fn js_lit(l: &rex::types::typed::Lit) -> String {
    use rex::types::typed::Lit;
    match l {
        Lit::Unit => js_str("u"),
        Lit::Str(s) => format!("encodeText({})", js_str(s)),
        Lit::Atom(a) => format!("encodeAtom({})", js_str(a)),
        Lit::Int(n) => js_str(&format!("i:{n}")),
        Lit::Decimal(d) => js_str(&format!("m:{d}")),
        Lit::Date { year, month, day } => js_str(&format!("d:{year:04}-{month:02}-{day:02}")),
    }
}

/// `on keydown.enter` -> `"keydown"` (event modifiers are handled in the
/// listener body, not the event name).
fn dom_event(ev: &EventBinding) -> String {
    ev.dom_event.clone()
}

/// A key selector (`enter`, `escape`, `up`) as a `KeyboardEvent.key` value.
fn key_name(m: &str) -> String {
    match m {
        "enter" => "Enter".into(),
        "escape" | "esc" => "Escape".into(),
        "tab" => "Tab".into(),
        "space" => " ".into(),
        "up" | "down" | "left" | "right" => format!("Arrow{}{}", m[..1].to_uppercase(), &m[1..]),
        _ if m.len() == 1 => m.to_string(),
        _ => format!("{}{}", m[..1].to_uppercase(), &m[1..]),
    }
}

/// The `rex-dom` decode function for a bind's wire encoding (an `Id` passes
/// through already-encoded, so it shares `decodeText`'s no-op-on-non-`t:`
/// behavior rather than needing its own decoder).
fn decode_fn(encoding: Encoding) -> &'static str {
    match encoding {
        Encoding::Text | Encoding::Id => "decodeText",
        Encoding::Int => "decodeInt",
        Encoding::Money => "decodeMoney",
        Encoding::Atom => "decodeAtom",
    }
}

/// A child-index navigation expression from `root` down a path.
fn nav_expr(root: &str, path: &[usize]) -> String {
    if path.is_empty() {
        return root.to_string();
    }
    let mut expr = root.to_string();
    for &i in path {
        expr = format!("({expr}.childNodes[{i}] as HTMLElement)");
    }
    expr
}

/// A JS/TS-safe variable name for a `#`/`@`-separated level name.
fn var_name(name: &str) -> String {
    let mut s = String::from("shape_");
    for ch in name.chars() {
        s.push(if ch.is_ascii_alphanumeric() { ch } else { '_' });
    }
    s
}

/// The app name in a program import specifier: `./dir/board.rex?raw` -> `board`.
fn program_name(import: &str) -> String {
    let file = import.rsplit('/').next().unwrap_or(import);
    let stem = file.split('?').next().unwrap_or(file);
    stem.strip_suffix(".rex").unwrap_or(stem).to_string()
}

/// A JSON/JS string literal.
fn js_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out.push('"');
    out
}
