// GENERATED by rex-codegen — do not edit by hand.
import init, { RexApp } from "./pkg/rex_wasm.js";
import {
  BrowserDriver, Shaper, parseStepJson, encodeText, decodeText, encodeAtom, encodeInt, encodeMoney, encodeRel,
  decodeInt, decodeMoney, decodeAtom,
  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,
  type DomDriver, type ShapeNode,
} from "rex-dom";
import { boot, IndexedDbAdapter, MemoryAdapter, profiler, programKey } from "rex-runtime";
import PROGRAM from "./board.rex?raw";

await init();
const store = new URLSearchParams(location.search).has("ephemeral") || import.meta.env.VITE_REX_PERSIST === "0"
  ? new MemoryAdapter()
  : new IndexedDbAdapter(programKey("board", PROGRAM));
const app = await boot({ RexApp, program: PROGRAM, adapter: store });
const prof = profiler(new URLSearchParams(location.search).has("profile"));
(window as unknown as { __rexApp: RexApp }).__rexApp = app;
const driver = new BrowserDriver();
const container = document.getElementById("app")!;
const apply = (json: string) => shaper.applyStep(parseStepJson(json));
function dispatch(name: string, args: Record<string, unknown>): string[] {
  const res = prof
    ? prof.dispatch(name, () => app.dispatch(name, JSON.stringify(args)), (r: any) => shaper.applyStep(r.deltas.views))
    : JSON.parse(app.dispatch(name, JSON.stringify(args)));
  if (!prof) shaper.applyStep(res.deltas.views);
  return res.ids as string[];
}

let proto_shape_main_list_card: HTMLElement | undefined;
function build_shape_main_list_card(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("div");
  e0.className = "card";
  const e1 = d.createElement("input");
  e0.appendChild(e1);
  const e2 = d.createElement("button");
  e2.appendChild(document.createTextNode("×"));
  e0.appendChild(e2);
  return e0;
}

const shape_main_list_card: ShapeNode<HTMLElement> = {
  name: "main#list#card",
  membershipView: "main#list#card",
  orderView: "main#list#card#order",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_list_card ??= build_shape_main_list_card(d));
    e0.dataset.key = key;
    makeDraggable(e0, key);
    ((e0.childNodes[0] as HTMLElement)).addEventListener("change", (ev) => {
      const v = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      _ids.push(...dispatch("RenameCard", { "card": key, "title": v }));
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("DeleteCard", { "card": key }));
    });
    return e0;
  },
  attrs: [
    {
      view: "main#list#card#title",
      apply: (_d, el, v) => {
        const _i = ((el.childNodes[0] as HTMLElement)) as HTMLInputElement;
        const _s = String(decodeText(v));
        if (_i.value !== _s) _i.value = _s;
        _i.defaultValue = _s;
      },
    },
  ],
  children: [],
};

let proto_shape_main_list: HTMLElement | undefined;
function build_shape_main_list(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("section");
  e0.className = "list";
  const e1 = d.createElement("header");
  const e2 = d.createElement("span");
  e1.appendChild(e2);
  const e3 = d.createElement("span");
  e3.className = "count";
  e1.appendChild(e3);
  const e4 = d.createElement("button");
  e4.appendChild(document.createTextNode("+ card"));
  e1.appendChild(e4);
  e0.appendChild(e1);
  return e0;
}

const shape_main_list: ShapeNode<HTMLElement> = {
  name: "main#list",
  membershipView: "main#list",
  orderView: "main#list#order",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_list ??= build_shape_main_list(d));
    e0.dataset.key = key;
    makeDropTarget(e0);
    (e0).addEventListener("drop", (ev) => {
      const card = dragValue(ev);
      const pos = encodeText(dropPos(shaper, "main#list#card", key, (ev as DragEvent).clientY, card));
      const _ids: string[] = [];
      _ids.push(...dispatch("MoveCard", { "card": card, "list": key, "pos": pos }));
      maybeRebalance(app, apply, shaper, "main#list#card", key, "pos", encodeText);
    });
    (((e0.childNodes[0] as HTMLElement).childNodes[2] as HTMLElement)).addEventListener("click", (ev) => {
      const pos = encodeText(endOf(shaper, "main#list#card", key));
      const _ids: string[] = [];
      _ids.push(...dispatch("AddCard", { "list": key, "pos": pos }));
      for (const _id of _ids) { const _el = shaper.el("main#list#card", _id); if (_el) { (_el.querySelector("input, textarea") as HTMLElement | null)?.focus(); break; } }
      maybeRebalance(app, apply, shaper, "main#list#card", key, "pos", encodeText);
    });
    return e0;
  },
  attrs: [
    {
      view: "main#list#title",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
    {
      view: "main#list#bind1",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).textContent = String(decodeInt(v));
      },
    },
  ],
  children: [shape_main_list_card],
};

const shaper = new Shaper<HTMLElement>(driver, container, [shape_main_list]);
shaper.applyStep(parseStepJson(app.snapshot()));
