// GENERATED by rex-codegen — do not edit by hand.
import init, { RexApp } from "./pkg/rex_wasm.js";
import {
  BrowserDriver, Shaper, parseStepJson, encodeText, decodeText, encodeAtom, encodeInt, encodeMoney, encodeRel,
  decodeInt, decodeMoney, decodeAtom,
  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,
  type ShapeNode,
} from "rex-dom";
import { boot, IndexedDbAdapter, MemoryAdapter, programKey } from "rex-runtime";
import PROGRAM from "./app.rex?raw";

await init();
const store = new URLSearchParams(location.search).has("ephemeral")
  ? new MemoryAdapter()
  : new IndexedDbAdapter(programKey("app", PROGRAM));
const app = await boot({ RexApp, program: PROGRAM, adapter: store });
(window as unknown as { __rexApp: RexApp }).__rexApp = app;
const driver = new BrowserDriver();
const container = document.getElementById("app")!;
const apply = (json: string) => shaper.applyStep(parseStepJson(json));
function dispatch(name: string, args: Record<string, unknown>): string[] {
  const res = JSON.parse(app.dispatch(name, JSON.stringify(args)));
  shaper.applyStep(res.deltas.views);
  return res.ids as string[];
}

const shape_main_unit_if1_visible: ShapeNode<HTMLElement> = {
  name: "main#unit#if1#visible",
  membershipView: "main#unit#if1#visible",
  orderView: "main#unit#if1#visible#order",
  slot: (root) => (root.childNodes[2] as HTMLElement),
  template: (d, key) => {
    const e0 = d.createElement("li");
    const e1 = d.createElement("div");
    e1.className = "view";
    const e2 = d.createElement("input");
    e2.className = "toggle";
    e2.setAttribute("type", "checkbox");
    e1.appendChild(e2);
    const e3 = d.createElement("label");
    e1.appendChild(e3);
    const e4 = d.createElement("button");
    e4.className = "destroy";
    e1.appendChild(e4);
    e0.appendChild(e1);
    const e5 = d.createElement("input");
    e5.className = "edit";
    e0.appendChild(e5);
    e0.dataset.key = key;
    (((e0.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).addEventListener("change", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("ToggleTodo", { "t": key }));
    });
    (((e0.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).addEventListener("dblclick", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("local#TodoItem#editing#set", { "t": key, "#value": encodeAtom("True") }));
      (e0.querySelector(".edit") as HTMLElement | null)?.focus();
    });
    (((e0.childNodes[0] as HTMLElement).childNodes[2] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("DeleteTodo", { "t": key }));
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("keydown", (ev) => {
      if (!["Enter"].includes((ev as KeyboardEvent).key)) return;
      const v = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      _ids.push(...dispatch("EditTodo", { "t": key, "text": v }));
      _ids.push(...dispatch("local#TodoItem#editing#set", { "t": key, "#value": encodeAtom("False") }));
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("keydown", (ev) => {
      if (!["Escape"].includes((ev as KeyboardEvent).key)) return;
      const _ids: string[] = [];
      _ids.push(...dispatch("local#TodoItem#editing#set", { "t": key, "#value": encodeAtom("False") }));
      { const _i = ev.currentTarget as HTMLInputElement; _i.value = _i.defaultValue; }
    });
    ((e0.childNodes[1] as HTMLElement)).addEventListener("blur", (ev) => {
      const v = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      _ids.push(...dispatch("EditTodo", { "t": key, "text": v }));
      _ids.push(...dispatch("local#TodoItem#editing#set", { "t": key, "#value": encodeAtom("False") }));
    });
    return e0;
  },
  attrs: [
    {
      view: "main#unit#if1#visible#gate3",
      presence: true,
      apply: (_d, el, v) => {
        (el).classList.toggle("completed", v !== undefined);
      },
    },
    {
      view: "main#unit#if1#visible#gate4",
      presence: true,
      apply: (_d, el, v) => {
        (el).classList.toggle("editing", v !== undefined);
      },
    },
    {
      view: "main#unit#if1#visible#completed",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement) as HTMLInputElement).checked = (v === encodeAtom("True"));
      },
    },
    {
      view: "main#unit#if1#visible#text",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
    {
      view: "main#unit#if1#visible#text",
      apply: (_d, el, v) => {
        const _i = ((el.childNodes[1] as HTMLElement)) as HTMLInputElement;
        const _s = String(decodeText(v));
        if (_i.value !== _s) _i.value = _s;
        _i.defaultValue = _s;
      },
    },
  ],
  children: [],
};

const shape_main_unit_if1: ShapeNode<HTMLElement> = {
  name: "main#unit#if1",
  membershipView: "main#unit#if1",
  template: (d, key) => {
    const e0 = d.createElement("section");
    e0.className = "main";
    const e1 = d.createElement("input");
    e1.className = "toggle-all";
    e1.setAttribute("id", "toggle-all");
    e1.setAttribute("type", "checkbox");
    e0.appendChild(e1);
    const e2 = d.createElement("label");
    e2.setAttribute("for", "toggle-all");
    e2.appendChild(document.createTextNode("Mark all as complete"));
    e0.appendChild(e2);
    const e3 = d.createElement("ul");
    e3.className = "todo-list";
    e0.appendChild(e3);
    e0.dataset.key = key;
    ((e0.childNodes[0] as HTMLElement)).addEventListener("change", (ev) => {
      const done = ((ev.currentTarget as HTMLInputElement).checked ? encodeAtom("True") : encodeAtom("False"));
      const _ids: string[] = [];
      _ids.push(...dispatch("ToggleAll", { "done": done }));
    });
    return e0;
  },
  attrs: [
    {
      view: "main#unit#if1#gate2",
      presence: true,
      apply: (_d, el, v) => {
        ((el.childNodes[0] as HTMLElement) as any).checked = v !== undefined;
      },
    },
  ],
  children: [shape_main_unit_if1_visible],
};

const shape_main_unit_if5_if10: ShapeNode<HTMLElement> = {
  name: "main#unit#if5#if10",
  membershipView: "main#unit#if5#if10",
  template: (d, key) => {
    const e0 = d.createElement("button");
    e0.className = "clear-completed";
    e0.appendChild(document.createTextNode("Clear completed"));
    e0.dataset.key = key;
    (e0).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("ClearCompleted", {  }));
    });
    return e0;
  },
  attrs: [
  ],
  children: [],
};

const shape_main_unit_if5: ShapeNode<HTMLElement> = {
  name: "main#unit#if5",
  membershipView: "main#unit#if5",
  template: (d, key) => {
    const e0 = d.createElement("footer");
    e0.className = "footer";
    const e1 = d.createElement("span");
    e1.className = "todo-count";
    const e2 = d.createElement("strong");
    e1.appendChild(e2);
    e1.appendChild(document.createTextNode(" items left"));
    e0.appendChild(e1);
    const e3 = d.createElement("ul");
    e3.className = "filters";
    const e4 = d.createElement("li");
    const e5 = d.createElement("a");
    e5.appendChild(document.createTextNode("All"));
    e4.appendChild(e5);
    e3.appendChild(e4);
    const e6 = d.createElement("li");
    const e7 = d.createElement("a");
    e7.appendChild(document.createTextNode("Active"));
    e6.appendChild(e7);
    e3.appendChild(e6);
    const e8 = d.createElement("li");
    const e9 = d.createElement("a");
    e9.appendChild(document.createTextNode("Completed"));
    e8.appendChild(e9);
    e3.appendChild(e8);
    e0.appendChild(e3);
    e0.dataset.key = key;
    ((((e0.childNodes[1] as HTMLElement).childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("SetFilter", { "f": encodeAtom("All") }));
    });
    ((((e0.childNodes[1] as HTMLElement).childNodes[1] as HTMLElement).childNodes[0] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("SetFilter", { "f": encodeAtom("Active") }));
    });
    ((((e0.childNodes[1] as HTMLElement).childNodes[2] as HTMLElement).childNodes[0] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      _ids.push(...dispatch("SetFilter", { "f": encodeAtom("Completed") }));
    });
    return e0;
  },
  attrs: [
    {
      view: "main#unit#if5#bind6",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).textContent = String(decodeInt(v));
      },
    },
    {
      view: "main#unit#if5#gate7",
      presence: true,
      apply: (_d, el, v) => {
        ((((el.childNodes[1] as HTMLElement).childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).classList.toggle("selected", v !== undefined);
      },
    },
    {
      view: "main#unit#if5#gate8",
      presence: true,
      apply: (_d, el, v) => {
        ((((el.childNodes[1] as HTMLElement).childNodes[1] as HTMLElement).childNodes[0] as HTMLElement)).classList.toggle("selected", v !== undefined);
      },
    },
    {
      view: "main#unit#if5#gate9",
      presence: true,
      apply: (_d, el, v) => {
        ((((el.childNodes[1] as HTMLElement).childNodes[2] as HTMLElement).childNodes[0] as HTMLElement)).classList.toggle("selected", v !== undefined);
      },
    },
  ],
  children: [shape_main_unit_if5_if10],
};

const shape_main_unit: ShapeNode<HTMLElement> = {
  name: "main#unit",
  membershipView: "main#unit",
  template: (d, key) => {
    const e0 = d.createElement("section");
    e0.className = "todoapp";
    const e1 = d.createElement("header");
    e1.className = "header";
    const e2 = d.createElement("h1");
    e2.appendChild(document.createTextNode("todos"));
    e1.appendChild(e2);
    const e3 = d.createElement("input");
    e3.className = "new-todo";
    e3.setAttribute("placeholder", "What needs to be done?");
    e3.setAttribute("autofocus", "");
    setTimeout(() => e3.focus(), 0);
    e1.appendChild(e3);
    e0.appendChild(e1);
    e0.dataset.key = key;
    (((e0.childNodes[0] as HTMLElement).childNodes[1] as HTMLElement)).addEventListener("keydown", (ev) => {
      if (!["Enter"].includes((ev as KeyboardEvent).key)) return;
      const text = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      _ids.push(...dispatch("AddTodo", { "text": text }));
      (ev.currentTarget as HTMLInputElement).value = "";
    });
    return e0;
  },
  attrs: [
  ],
  children: [shape_main_unit_if1, shape_main_unit_if5],
};

const shaper = new Shaper<HTMLElement>(driver, container, [shape_main_unit]);
shaper.applyStep(parseStepJson(app.snapshot()));
