// GENERATED by rex-codegen — do not edit by hand.
import init, { RexApp } from "rex-runtime/wasm";
import {
  BrowserDriver, Shaper, encodeText, decodeText, encodeAtom, encodeInt, encodeMoney, encodeRel,
  decodeInt, decodeMoney, decodeAtom,
  makeDraggable, makeDropTarget, dragValue, endOf, dropPos, maybeRebalance,
  type DomDriver, type EventArg, type ShapeNode,
} from "rex-dom";
import { boot, IndexedDbAdapter, MemoryAdapter, profiler, programKey } from "rex-runtime";
import PROGRAM from "./app.rex?raw";

await init();
const store = new URLSearchParams(location.search).has("ephemeral") || import.meta.env.VITE_REX_PERSIST === "0"
  ? new MemoryAdapter()
  : new IndexedDbAdapter(programKey("app", PROGRAM));
const prof = profiler(new URLSearchParams(location.search).has("profile"));
const engine = await boot({ RexApp, program: PROGRAM, adapter: store, profiler: prof });
(window as unknown as { __rexApp: typeof engine }).__rexApp = engine;
const driver = new BrowserDriver();
const container = document.getElementById("app")!;
function dispatch(name: string, args: Record<string, EventArg>): readonly string[] | null {
  let res;
  try {
    res = engine.dispatch(name, args);
  } catch (refused) {
    console.warn(`[rex] event ${name} was refused:`, refused);
    return null;
  }
  if (prof) prof.shaper(() => shaper.applyStep(res.deltas));
  else shaper.applyStep(res.deltas);
  return res.ids;
}

let proto_shape_main_unit_user: HTMLElement | undefined;
function build_shape_main_unit_user(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("button");
  return e0;
}

const shape_main_unit_user: ShapeNode<HTMLElement> = {
  name: "main#unit#user",
  membershipView: "main#unit#user",
  slot: (root) => (root.childNodes[2] as HTMLElement),
  slotKey: "2",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_unit_user ??= build_shape_main_unit_user(d));
    e0.dataset.key = key;
    (e0).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      { const _r = dispatch("UserSelected", { "user": key }); if (_r === null) return; _ids.push(..._r); }
    });
    return e0;
  },
  attrs: [
    {
      view: "main#unit#user#gate2",
      presence: true,
      apply: (_d, el, v) => {
        (el).classList.toggle("selected", v !== undefined);
      },
    },
    {
      view: "main#unit#user#name",
      apply: (_d, el, v) => {
        (el).textContent = String(decodeText(v));
      },
    },
  ],
  children: [],
};

let proto_shape_main_unit_message_like: HTMLElement | undefined;
function build_shape_main_unit_message_like(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("div");
  e0.appendChild(document.createTextNode(""));
  e0.appendChild(document.createTextNode(" likes this!"));
  return e0;
}

const shape_main_unit_message_like: ShapeNode<HTMLElement> = {
  name: "main#unit#message#like",
  membershipView: "main#unit#message#like",
  slot: (root) => (root.childNodes[2] as HTMLElement),
  slotKey: "2",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_unit_message_like ??= build_shape_main_unit_message_like(d));
    e0.dataset.key = key;
    return e0;
  },
  attrs: [
    {
      view: "main#unit#message#like#bind3",
      apply: (_d, el, v) => {
        ((el.childNodes[0] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
  ],
  children: [],
};

let proto_shape_main_unit_message_if4: HTMLElement | undefined;
function build_shape_main_unit_message_if4(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("button");
  e0.appendChild(document.createTextNode("Like!"));
  return e0;
}

const shape_main_unit_message_if4: ShapeNode<HTMLElement> = {
  name: "main#unit#message#if4",
  membershipView: "main#unit#message#if4",
  slot: (root) => (root.childNodes[3] as HTMLElement),
  slotKey: "3",
  template: (d, key, ancestors) => {
    const e0 = d.clone(proto_shape_main_unit_message_if4 ??= build_shape_main_unit_message_if4(d));
    e0.dataset.key = key;
    (e0).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      { const _r = dispatch("MessageLiked", { "msg": ancestors[0]! }); if (_r === null) return; _ids.push(..._r); }
    });
    return e0;
  },
  attrs: [
  ],
  children: [],
};

let proto_shape_main_unit_message_if5: HTMLElement | undefined;
function build_shape_main_unit_message_if5(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("td");
  const e1 = d.createElement("button");
  e1.appendChild(document.createTextNode("Delete"));
  e0.appendChild(e1);
  return e0;
}

const shape_main_unit_message_if5: ShapeNode<HTMLElement> = {
  name: "main#unit#message#if5",
  membershipView: "main#unit#message#if5",
  template: (d, key, ancestors) => {
    const e0 = d.clone(proto_shape_main_unit_message_if5 ??= build_shape_main_unit_message_if5(d));
    e0.dataset.key = key;
    ((e0.childNodes[0] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      { const _r = dispatch("MessageDeleted", { "msg": ancestors[0]! }); if (_r === null) return; _ids.push(..._r); }
    });
    return e0;
  },
  attrs: [
  ],
  children: [],
};

let proto_shape_main_unit_message: HTMLElement | undefined;
function build_shape_main_unit_message(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("tr");
  const e1 = d.createElement("td");
  e1.appendChild(document.createTextNode(""));
  e1.appendChild(document.createTextNode(":"));
  e0.appendChild(e1);
  const e2 = d.createElement("td");
  e0.appendChild(e2);
  const e3 = d.createElement("td");
  e0.appendChild(e3);
  const e4 = d.createElement("td");
  e0.appendChild(e4);
  return e0;
}

const shape_main_unit_message: ShapeNode<HTMLElement> = {
  name: "main#unit#message",
  membershipView: "main#unit#message",
  orderView: "main#unit#message#order",
  slot: (root) => (root.childNodes[3] as HTMLElement),
  slotKey: "3",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_unit_message ??= build_shape_main_unit_message(d));
    e0.dataset.key = key;
    return e0;
  },
  attrs: [
    {
      view: "main#unit#message#sender.name",
      apply: (_d, el, v) => {
        (((el.childNodes[0] as HTMLElement).childNodes[0] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
    {
      view: "main#unit#message#text",
      apply: (_d, el, v) => {
        ((el.childNodes[1] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
  ],
  children: [shape_main_unit_message_like, shape_main_unit_message_if4, shape_main_unit_message_if5],
};

let proto_shape_main_unit_if6: HTMLElement | undefined;
function build_shape_main_unit_if6(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("input");
  e0.className = "send-message";
  e0.setAttribute("placeholder", "Say something ...");
  return e0;
}

const shape_main_unit_if6: ShapeNode<HTMLElement> = {
  name: "main#unit#if6",
  membershipView: "main#unit#if6",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_unit_if6 ??= build_shape_main_unit_if6(d));
    e0.dataset.key = key;
    (e0).addEventListener("keydown", (ev) => {
      if (!["Enter"].includes((ev as KeyboardEvent).key)) return;
      const p_text = encodeText((ev.currentTarget as HTMLInputElement).value);
      const _ids: string[] = [];
      { const _r = dispatch("MessageSent", { "text": p_text }); if (_r === null) return; _ids.push(..._r); }
      (ev.currentTarget as HTMLInputElement).value = "";
    });
    return e0;
  },
  attrs: [
  ],
  children: [],
};

let proto_shape_main_unit: HTMLElement | undefined;
function build_shape_main_unit(d: DomDriver<HTMLElement>): HTMLElement {
  const e0 = d.createElement("div");
  e0.className = "chat-root";
  const e1 = d.createElement("h1");
  e1.appendChild(document.createTextNode("Chat App"));
  e0.appendChild(e1);
  const e2 = d.createElement("div");
  e2.className = "toolbar";
  const e3 = d.createElement("button");
  e3.appendChild(document.createTextNode("Load Synthetic Data"));
  e2.appendChild(e3);
  const e4 = d.createElement("span");
  e2.appendChild(e4);
  e0.appendChild(e2);
  const e5 = d.createElement("div");
  e5.className = "users";
  e0.appendChild(e5);
  const e6 = d.createElement("table");
  e0.appendChild(e6);
  return e0;
}

const shape_main_unit: ShapeNode<HTMLElement> = {
  name: "main#unit",
  membershipView: "main#unit",
  template: (d, key) => {
    const e0 = d.clone(proto_shape_main_unit ??= build_shape_main_unit(d));
    e0.dataset.key = key;
    (((e0.childNodes[1] as HTMLElement).childNodes[0] as HTMLElement)).addEventListener("click", (ev) => {
      const _ids: string[] = [];
      { const _r = dispatch("SeedSynthetic", {  }); if (_r === null) return; _ids.push(..._r); }
    });
    return e0;
  },
  attrs: [
    {
      view: "main#unit#bind1",
      apply: (_d, el, v) => {
        (((el.childNodes[1] as HTMLElement).childNodes[1] as HTMLElement)).textContent = String(decodeText(v));
      },
    },
  ],
  children: [shape_main_unit_user, shape_main_unit_message, shape_main_unit_if6],
};

const shaper = new Shaper<HTMLElement>(driver, container, [shape_main_unit]);
shaper.applyStep(engine.snapshot());
